name: Users Service CI Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Set up environment file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build, tag, and push image to Google Container Registry
        env:
          IMAGE_TAG: latest
        run: |
          docker build -f task-management-system/users.Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.USERS_GCR }}:$IMAGE_TAG task-management-system/
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.USERS_GCR }}:$IMAGE_TAG
